name: Node.js NPM Upgrade

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs: 
  npm_upgrade:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Upgrade NPM packages
      run: npm update

    - name: Check for changes
      id: git_status
      run: |
        git diff --quiet || echo "::set-output name=changed::true"
      continue-on-error: true

    - name: Commit changes
      if: steps.git_status.outputs.changed == 'true'
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git remote add origin https://$GITHUB_ACTOR:GITHUB_TOKEN@github.com/GITHUB_ACTOR/$GITHUB_REPOSITORY.git

        git add .
        git commit -m "chore: Upgrade NPM packages"
        git push
      

    - name: Create Pull Request
      if: steps.git_status.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'chore: Upgrade NPM packages'
        body: |
          This PR automatically upgrades NPM packages.
        labels: 'auto-upgrade'
