name: Node.js NPM Upgrade

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT: ${{ secrets.PAT }}

jobs: 
  npm_upgrade:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout New-Branch
      run: git checkout -B workflow/npm-install-$GITHUB_RUN_NUMBER

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Upgrade NPM packages
      run: npm update

    - name: Check for changes
      id: git_status
      run: |
        git diff --quiet || echo "::set-output name=changed::true"
      continue-on-error: true

    - name: Commit changes
      if: steps.git_status.outputs.changed == 'true'
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "chore: Upgrade NPM packages"
        git remote -v
        git remote set-url origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git push --set-upstream origin workflow/npm-install-$GITHUB_RUN_NUMBER
      

    - name: Create Pull Request
      if: steps.git_status.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: $GITHUB_TOKEN
        title: 'Upgrade NPM packages'
        branch: workflow/npm-install-$GITHUB_RUN_NUMBER
        base: master
        body: "Diese Änderungen wurden automatisch erstellt."
        labels: 'auto-upgrade'
